src/hapi/pipelines/database/dbadmin1.py
src/hapi/pipelines/database/dbadmin2.py
src/hapi/pipelines/database/dbagerange.py
src/hapi/pipelines/database/dbdataset.py
src/hapi/pipelines/database/dbgender.py
src/hapi/pipelines/database/dblocation.py
src/hapi/pipelines/database/dboperationalpresence.py
src/hapi/pipelines/database/dborg.py
src/hapi/pipelines/database/dborgtype.py
src/hapi/pipelines/database/dbpopulation.py
src/hapi/pipelines/database/dbresource.py
src/hapi/pipelines/database/dbsector.py

Converted tables names to snake case

---

src/hapi/pipelines/database/dbadmin1.py
src/hapi/pipelines/database/dbadmin2.py
src/hapi/pipelines/database/dboperationalpresence.py
src/hapi/pipelines/database/dborg.py
src/hapi/pipelines/database/dbpopulation.py
src/hapi/pipelines/database/dbresource.py

Update the DB references to match v1.1.1, as discussed [here](https://humdata.slack.com/archives/C04UD1VPY2G/p1693524576161739)

Fix DB imports and references 

---

src/hapi/pipelines/app/pipelines.py
src/hapi/pipelines/app/project_configuration.yaml
src/hapi/pipelines/utilities/admins.py
src/hapi/pipelines/utilities/locations.py

This has all the changes in the Tables in SQLAlchemy ORM format PR https://github.com/OCHA-DAP/hapi-pipelines/pull/8 as well as code to populate admin tables
This is a very inefficient implementation at present

Admin in db

---

src/hapi/pipelines/app/pipelines.py
src/hapi/pipelines/utilities/metadata.py

Refactor the metadata collection to its own class, and populate the latest schema.
@mcarans I think that the download URL will need to be added to the scraper output

Refactor metadata

---

pyproject.toml
requirements.txt

@turnerm Feel free to merge this one if all good since I won't get to look at it till next week

No longer need GitHub requirements for HDX Python Scraper or Country

---

pyproject.toml

Missed setting hdx-python-database to latest version

Fix database package version

---

src/hapi/pipelines/app/pipelines.py
src/hapi/pipelines/app/project_configuration.yaml
src/hapi/pipelines/utilities/admins.py
src/hapi/pipelines/utilities/metadata.py
src/hapi/pipelines/utilities/population.py

This PR builds on the population one, adding an admin1 population dataset and populating the table.
The only thing that I'm not super happy with is how to distinguish between an admin1 and admin2 dataset at the results level. Right now I just take the first pcode and check against the lookup tables, but is the level information available in some dictionary somewhere in the scraper results?

Add pop admin 1

---

README.md
pyproject.toml
requirements.txt

Update the reqs and README to use the latest in hapi-schemas

Switch to postgres

---

pyproject.toml
requirements.txt
src/hapi/pipelines/app/pipelines.py
src/hapi/pipelines/database/db_admin1.py
src/hapi/pipelines/database/db_admin2.py
src/hapi/pipelines/database/db_gender.py
src/hapi/pipelines/database/db_operational_presence.py
src/hapi/pipelines/database/db_org.py
src/hapi/pipelines/database/db_population.py
src/hapi/pipelines/utilities/metadata.py
src/hapi/pipelines/utilities/population.py

Updated for the changes in this PR against HDX Python Scraper:
https://github.com/OCHA-DAP/hdx-python-scraper/pull/23#issuecomment-1728673859
(This includes the nullable PR.)

get_hapi_metadata, get_hapi_results now return dictionaries

---

CHANGELOG.md
pyproject.toml
requirements.txt
src/hapi/pipelines/app/__main__.py
src/hapi/pipelines/app/build_db_views.py

I'll remove the requirement pointing to the branch once [this PR](https://github.com/OCHA-DAP/hapi-sqlalchemy-schema/pull/7) is merged. That should hopefully fix the tests.

Hapi 224 remove hdx python database dep

---

CHANGELOG.md
pyproject.toml
requirements.txt
src/hapi/pipelines/database/metadata.py

Leaving draft until the two dependencies are released

HAPI-234 dataset provider info

---

CHANGELOG.md
src/hapi/pipelines/database/population.py
src/hapi/pipelines/utilities/process_config_defaults.py
tests/test_population.py
tests/test_process_config_defaults.py
tests/test_process_config_defaults.yaml

Just a couple of unit tests to make sure some edge cases were covered . I also re-ordered the functions in process_config_defaults to reflect the order in which they are called, and made a change to cover the "list" default parameter.

HAPI-159 unit tests

---

.github/workflows/db_export.yaml
.github/workflows/run-python-tests.yaml
dump_views.sh
requirements.txt

HDXDSYS-685 Output csvs

---

CHANGELOG.md
pyproject.toml
requirements.txt
src/hapi/pipelines/database/food_security.py
src/hapi/pipelines/database/humanitarian_needs.py
src/hapi/pipelines/database/metadata.py
src/hapi/pipelines/database/national_risk.py
src/hapi/pipelines/database/operational_presence.py
src/hapi/pipelines/database/population.py
tests/test_main.py

@turnerm Is 0.8.0 the right version here?

Update dataset and resource table ids

---

CHANGELOG.md
src/hapi/pipelines/utilities/mappings.py
tests/test_mappings.py

Making and merging straight away as it is a copy of this approved PR https://github.com/OCHA-DAP/hapi-pipelines/pull/91

Prevent phonetic matching of short names (to main instead of develop branch)

---

CHANGELOG.md
requirements.txt
src/hapi/pipelines/database/humanitarian_needs.py
src/hapi/pipelines/database/operational_presence.py
src/hapi/pipelines/utilities/logging_helpers.py

Make operational presence output errors at end
Use same format for humanitarian needs and operational presence by making utility functions
Suggest we use and add functions so keep log output consistent

HDXDSYS-749 Output warnings and errors at end in consistent format

---

CHANGELOG.md
src/hapi/pipelines/app/pipelines.py
src/hapi/pipelines/configs/conflict_event.yaml
src/hapi/pipelines/database/conflict_event.py
tests/test_main.py

Filtering out problematic unit in ACLED data and flagging in the log for consistency.  I also realized the yaml wasn't producing results I was expecting so refactored to make all three resources appear in the database.  However, they are all linked to the same resource because the results only contain one resource per dataset (I've added a todo to address this).
cc @mcarans @turnerm

Update conflict pipeline and test

---

CHANGELOG.md
src/hapi/pipelines/configs/poverty_rate.yaml

I used the datagrid instead of the full HRP list to add the poverty rate countries, I've now included the missing ones.

Bugfix: add missing poverty rate countries

---

CHANGELOG.md
pyproject.toml
requirements.txt
src/hapi/pipelines/app/pipelines.py
src/hapi/pipelines/database/humanitarian_needs.py

HDXDSYS-800 Switch HNO to use prod HDX data

---

CHANGELOG.md
requirements.txt
src/hapi/pipelines/database/humanitarian_needs.py

Switch "POP" in HNO population status to "all" (I've confirmed with Javier that this is okay)

HDXDSYS-811 replace pop with all

---

.config/pre-commit-config.yaml
.github/workflows/run-python-tests.yaml
pyproject.toml
requirements.txt

HDXDSYS-834 Revert to pyphonetics by upgrading HDX Python Country

---

CHANGELOG.md
src/hapi/pipelines/configs/operational_presence.yaml

The Sudan 3W resource filename was changed today

Update Sudan 3W filename

---

CHANGELOG.md
src/hapi/pipelines/configs/core.yaml
src/hapi/pipelines/configs/operational_presence.yaml

Niger and Sudan have new 3W resources added in the past couple of days, this PR is to add them in

HDXDSYS-866 update ner and sdn 3w

---

CHANGELOG.md
pyproject.toml
requirements.txt
src/hapi/pipelines/configs/core.yaml
src/hapi/pipelines/database/operational_presence.py
src/hapi/pipelines/database/org.py
src/hapi/pipelines/utilities/mappings.py

Also HDX Python Country 3.7.5 has changes including not fuzzy matching < 4 character admins, so additional mappings required for 3 letter admins in HAPI Pipelines

HDXDSYS-868 Use normalise function from HDX Python Utilities

---

CHANGELOG.md
pyproject.toml
requirements.txt
src/hapi/pipelines/configs/core.yaml

Direct matching lookup uses normalised name for better matching and then passes the normalised name to fuzzy matching to avoid an extra call

HDXDSYS-873 get_pcode improvements (using newer HDX Python Country)

---

CHANGELOG.md
src/hapi/pipelines/configs/operational_presence.yaml

MOZ is now missing sector data and org name so will not make it into the database.
cc @turnerm

Update MOZ 3W data

---

CHANGELOG.md
src/hapi/pipelines/configs/operational_presence.yaml

Correct MOZ 3w parameters (in the time it took for the tests to run the resource was updated and reuploaded).
cc @turnerm

HDXDSYS-882 update moz 3w

---

CHANGELOG.md
src/hapi/pipelines/configs/operational_presence.yaml

Dataset name changed
cc @turnerm

HDXDSYS-882 update moz 3w again

---

CHANGELOG.md
src/hapi/pipelines/configs/conflict_event.yaml

File names for ETH changed back
cc @turnerm

Update file names in conflict data

---

CHANGELOG.md
src/hapi/pipelines/configs/population.yaml

Honduras population data has been updated. I checked that the full population pipeline works now.

HDXDSYS-896 fix hnd pop filenames

---

CHANGELOG.md
pyproject.toml
requirements.txt
src/hapi/pipelines/app/__main__.py
src/hapi/pipelines/app/pipelines.py
src/hapi/pipelines/database/conflict_event.py
src/hapi/pipelines/database/operational_presence.py
src/hapi/pipelines/database/org.py
src/hapi/pipelines/database/org_type.py
src/hapi/pipelines/database/sector.py
src/hapi/pipelines/utilities/mappings.py
tests/test_main.py
tests/test_mappings.py

Also add uncleaned names as keys to lookups
The branch is misnamed but I can only seem to change the local branch not the remote. Fuzzy stuff will come in a separate PR.

HDXDSYS-898 Refactor org code

---

CHANGELOG.md
src/hapi/pipelines/configs/operational_presence.yaml

Update HND 3W dataset

---

CHANGELOG.md
src/hapi/pipelines/database/humanitarian_needs.py

They needed to be batched by country

HDXDSYS-999 Fix logging of HNO warnings and errors

---

CHANGELOG.md
src/hapi/pipelines/configs/population.yaml

Please go ahead and merge if it's ok

HDXDSYS-1012 Fix population SLV failure

---

CHANGELOG.md
src/hapi/pipelines/configs/population.yaml

HDXDSYS-1224 fix HTI population adm2

---

requirements.txt
src/hapi/pipelines/database/idps.py

HDXDSYS-1537 HAPI Pipelines - fix failure for empty reportingDate in IDPs data

---

CHANGELOG.md
requirements.txt
src/hapi/pipelines/database/humanitarian_needs.py

HDXDSYS-1698 Ignore any rows with a populated Error column

---

CHANGELOG.md
pyproject.toml
requirements.txt
src/hapi/pipelines/database/admins.py
src/hapi/pipelines/database/humanitarian_needs.py
src/hapi/pipelines/database/operational_presence.py
src/hapi/pipelines/database/poverty_rate.py
tests/fixtures/input/download-global-mpi-trends.csv
tests/fixtures/input/download-global-mpi.csv
tests/test_main.py

@b-j-mills Prod dataset headers have been updated so hapi-pipelines-prod will need this change.

HDXDSYS-1318  Simplify poverty rate HAPI pipeline to read from global resource in global dataset on HDX

---

CHANGELOG.md
pyproject.toml
requirements.txt

Make schema change explicit in requirements

HDXDSYS-1733 schema update

---

CHANGELOG.md
pyproject.toml
requirements.txt

All this PR does is update requirements, the important one of which is HAPI schema

HDXDSYS-2028 Update HAPI schema so that appeal_type is longer to match new FTS type names
